name: 'Check Services'

description: 'Checks which services are affected by changes and outputs a matrix.'

outputs:
  matrix_services:
    description: 'JSON array of affected services.'
    value: ${{ steps.set_matrix.outputs.matrix_services }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install jq
      uses: dcarbone/install-jq-action@v3.0.1

    - name: Get changed directories and set matrix
      id: set_matrix
      shell: bash
      run: |
        # Get the base and feature branch SHAs
        base_branch=${{ github.event.pull_request.base.sha }}
        feature_branch=${{ github.event.pull_request.head.sha }}
    
        readarray -t changed_dirs < <(git diff --name-only $base_branch $feature_branch | awk -F'/' '{print $1"/"$2}' | sort -u)

        # Iterate through the changed directories
        for changed_dir in "${changed_dirs[@]}"; do
          # Use jq to find matching services and print only the key
          jq -r 'to_entries[] | select(.value.service_source_path | contains("'"$changed_dir"'")) | .key' build/config.json
        done | sort -u
